### ISSUE TITLE
Unable to open the project into VS2012

### ISSUE THREAD

**Issue by imperugo** [kazimanzurrashid/my-walletz-angular#1]
Hi,
When I try to open the project, I got this message

C:\Project\OOS\my-walletz-angular\source\MyWalletz\MyWalletz.csproj : error  : The imported project "C:\Project\OOS\my-walletz-angular\source\packages\Microsoft.Bcl.Build.1.0.7\tools\Microsoft.Bcl.Build.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Project\OOS\my-walletz-angular\source\MyWalletz\MyWalletz.csproj

Missing some files?

**Comment by kazimanzurrashid** [comment]
It looks like a common issue, checkout this link and try the workaround tab:
http://connect.microsoft.com/VisualStudio/feedback/details/788981/microsoft-bcl-build-targets-causes-project-loading-to-fail

**Comment by imperugo** [comment]
Yep, it works but you should update the repository with this workaround, otherwise the users must discard the local changes and update the csproj at every pull.

**Comment by kazimanzurrashid** [comment]
Ok done, do a pull.
